/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labosi.LV9.zadatak1;

import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.swing.JOptionPane;

/**
 *
 * @author Bole
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRezultat = new javax.swing.JButton();
        btnOduzimanje = new javax.swing.JButton();
        btnZbrajanje = new javax.swing.JButton();
        btnMnozenje = new javax.swing.JButton();
        btnDjeljenje = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnTocka = new javax.swing.JButton();
        btnZagradaZat = new javax.swing.JButton();
        btnZagradaOtv = new javax.swing.JButton();
        brnBrisanje = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        txtRacunanje = new javax.swing.JTextField();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        btnRezultat.setBackground(new java.awt.Color(255, 255, 255));
        btnRezultat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRezultat.setText("=");
        btnRezultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRezultatActionPerformed(evt);
            }
        });

        btnOduzimanje.setBackground(new java.awt.Color(255, 255, 255));
        btnOduzimanje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOduzimanje.setText("-");
        btnOduzimanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOduzimanjeActionPerformed(evt);
            }
        });

        btnZbrajanje.setBackground(new java.awt.Color(255, 255, 255));
        btnZbrajanje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnZbrajanje.setText("+");
        btnZbrajanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZbrajanjeActionPerformed(evt);
            }
        });

        btnMnozenje.setBackground(new java.awt.Color(255, 255, 255));
        btnMnozenje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMnozenje.setText("*");
        btnMnozenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMnozenjeActionPerformed(evt);
            }
        });

        btnDjeljenje.setBackground(new java.awt.Color(255, 255, 255));
        btnDjeljenje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDjeljenje.setText("/");
        btnDjeljenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDjeljenjeActionPerformed(evt);
            }
        });

        btnMod.setBackground(new java.awt.Color(255, 255, 255));
        btnMod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMod.setText("%");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setText("C");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(255, 255, 255));
        btn0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnTocka.setBackground(new java.awt.Color(255, 255, 255));
        btnTocka.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTocka.setText(".");
        btnTocka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTockaActionPerformed(evt);
            }
        });

        btnZagradaZat.setBackground(new java.awt.Color(255, 255, 255));
        btnZagradaZat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnZagradaZat.setText(")");
        btnZagradaZat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZagradaZatActionPerformed(evt);
            }
        });

        btnZagradaOtv.setBackground(new java.awt.Color(255, 255, 255));
        btnZagradaOtv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnZagradaOtv.setText("(");
        btnZagradaOtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZagradaOtvActionPerformed(evt);
            }
        });

        brnBrisanje.setBackground(new java.awt.Color(255, 255, 255));
        brnBrisanje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        brnBrisanje.setText("DEL");
        brnBrisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnBrisanjeActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        btn4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(255, 255, 255));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(255, 255, 255));
        btn7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        txtRacunanje.setEditable(false);

        btn8.setBackground(new java.awt.Color(255, 255, 255));
        btn8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(255, 255, 255));
        btn9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(255, 255, 255));
        btn5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(255, 255, 255));
        btn6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRacunanje, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnZagradaOtv, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn0)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn3)
                                    .addComponent(btnZagradaZat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTocka, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(brnBrisanje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOduzimanje, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(btnMnozenje, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(btnZbrajanje, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(btnRezultat, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(btnMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDjeljenje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {brnBrisanje, btn0, btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, btnDelete, btnMnozenje, btnOduzimanje, btnRezultat, btnTocka, btnZagradaOtv, btnZagradaZat, btnZbrajanje});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(txtRacunanje, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brnBrisanje)
                    .addComponent(btnDelete)
                    .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTocka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7)
                    .addComponent(btn8)
                    .addComponent(btn9)
                    .addComponent(btnDjeljenje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4)
                    .addComponent(btn5)
                    .addComponent(btn6)
                    .addComponent(btnMnozenje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3)
                    .addComponent(btnOduzimanje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0)
                    .addComponent(btnZagradaOtv)
                    .addComponent(btnZbrajanje)
                    .addComponent(btnZagradaZat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRezultat)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {brnBrisanje, btn0, btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, btnDelete, btnDjeljenje, btnMnozenje, btnMod, btnOduzimanje, btnRezultat, btnTocka, btnZagradaOtv, btnZagradaZat, btnZbrajanje});

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOduzimanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOduzimanjeActionPerformed
        if (txtRacunanje.getText().isEmpty() || txtRacunanje.getText() == null) {
            JOptionPane.showMessageDialog(null, "Prvo unesite broj");
            return;
        }
        if (txtRacunanje.getText().endsWith("+") || txtRacunanje.getText().endsWith("+") || txtRacunanje.getText().endsWith("-") || txtRacunanje.getText().endsWith("*") || txtRacunanje.getText().endsWith("/") || txtRacunanje.getText().endsWith(".") || txtRacunanje.getText().endsWith("%")) {
            txtRacunanje.setText(txtRacunanje.getText().substring(0, txtRacunanje.getText().length() - 1));
            txtRacunanje.setText(txtRacunanje.getText() + "-");
        } else {
            txtRacunanje.setText(txtRacunanje.getText() + "-");
        }
    }//GEN-LAST:event_btnOduzimanjeActionPerformed

    private void btnTockaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTockaActionPerformed
        if (txtRacunanje.getText().isEmpty() || txtRacunanje.getText() == null) {
            JOptionPane.showMessageDialog(null, "Prvo unesite broj");
            return;
        }
        if (txtRacunanje.getText().endsWith("+") || txtRacunanje.getText().endsWith("+") || txtRacunanje.getText().endsWith("-") || txtRacunanje.getText().endsWith("*") || txtRacunanje.getText().endsWith("/") || txtRacunanje.getText().endsWith(".") || txtRacunanje.getText().endsWith("%")) {
            txtRacunanje.setText(txtRacunanje.getText().substring(0, txtRacunanje.getText().length() - 1));
            txtRacunanje.setText(txtRacunanje.getText() + ".");
        } else {
            txtRacunanje.setText(txtRacunanje.getText() + ".");
        }
    }//GEN-LAST:event_btnTockaActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        txtRacunanje.setText(txtRacunanje.getText() + "0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnZagradaZatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZagradaZatActionPerformed
        txtRacunanje.setText(txtRacunanje.getText() + ")");
    }//GEN-LAST:event_btnZagradaZatActionPerformed

    private void btnRezultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRezultatActionPerformed
        if (txtRacunanje.getText().isEmpty() || txtRacunanje.getText() == null) {
            JOptionPane.showMessageDialog(null, "Niste ništa unijeli!");
            return;
        }
        ScriptEngineManager mgr = new ScriptEngineManager();
        ScriptEngine engine = mgr.getEngineByName("JavaScript");
        String izracun = txtRacunanje.getText();
        try {
            txtRacunanje.setText(engine.eval(izracun).toString());
        } catch (ScriptException ex) {
            JOptionPane.showMessageDialog(null, "Krivo ste unijeli zapis, pokusajte ponovno!");
        }

    }//GEN-LAST:event_btnRezultatActionPerformed

    private void btnZbrajanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZbrajanjeActionPerformed
        if (txtRacunanje.getText().isEmpty() || txtRacunanje.getText() == null) {
            JOptionPane.showMessageDialog(null, "Prvo unesite broj");
            return;
        }
        if (txtRacunanje.getText().endsWith("+") || txtRacunanje.getText().endsWith("+") || txtRacunanje.getText().endsWith("-") || txtRacunanje.getText().endsWith("*") || txtRacunanje.getText().endsWith("/") || txtRacunanje.getText().endsWith(".") || txtRacunanje.getText().endsWith("%")) {
            txtRacunanje.setText(txtRacunanje.getText().substring(0, txtRacunanje.getText().length() - 1));
            txtRacunanje.setText(txtRacunanje.getText() + "+");
        } else {
            txtRacunanje.setText(txtRacunanje.getText() + "+");
        }
    }//GEN-LAST:event_btnZbrajanjeActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        txtRacunanje.setText(txtRacunanje.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        txtRacunanje.setText(txtRacunanje.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        txtRacunanje.setText(txtRacunanje.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnMnozenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMnozenjeActionPerformed
        if (txtRacunanje.getText().isEmpty() || txtRacunanje.getText() == null) {
            JOptionPane.showMessageDialog(null, "Prvo unesite broj");
            return;
        }
        if (txtRacunanje.getText().endsWith("+") || txtRacunanje.getText().endsWith("+") || txtRacunanje.getText().endsWith("-") || txtRacunanje.getText().endsWith("*") || txtRacunanje.getText().endsWith("/") || txtRacunanje.getText().endsWith(".") || txtRacunanje.getText().endsWith("%")) {
            txtRacunanje.setText(txtRacunanje.getText().substring(0, txtRacunanje.getText().length() - 1));
            txtRacunanje.setText(txtRacunanje.getText() + "*");
        } else {
            txtRacunanje.setText(txtRacunanje.getText() + "*");
        }
    }//GEN-LAST:event_btnMnozenjeActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        txtRacunanje.setText(txtRacunanje.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        txtRacunanje.setText(txtRacunanje.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        txtRacunanje.setText(txtRacunanje.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        txtRacunanje.setText(txtRacunanje.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        txtRacunanje.setText(txtRacunanje.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        txtRacunanje.setText(txtRacunanje.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnDjeljenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDjeljenjeActionPerformed
        if (txtRacunanje.getText().isEmpty() || txtRacunanje.getText() == null) {
            JOptionPane.showMessageDialog(null, "Prvo unesite broj");
            return;
        }
        if (txtRacunanje.getText().endsWith("+") || txtRacunanje.getText().endsWith("+") || txtRacunanje.getText().endsWith("-") || txtRacunanje.getText().endsWith("*") || txtRacunanje.getText().endsWith("/") || txtRacunanje.getText().endsWith(".") || txtRacunanje.getText().endsWith("%")) {
            txtRacunanje.setText(txtRacunanje.getText().substring(0, txtRacunanje.getText().length() - 1));
            txtRacunanje.setText(txtRacunanje.getText() + "/");
        } else {
            txtRacunanje.setText(txtRacunanje.getText() + "/");
        }
    }//GEN-LAST:event_btnDjeljenjeActionPerformed

    private void brnBrisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnBrisanjeActionPerformed
        if (txtRacunanje.getText() != null && txtRacunanje.getText().length() > 0) {
            txtRacunanje.setText(txtRacunanje.getText().substring(0, txtRacunanje.getText().length() - 1));
        }
    }//GEN-LAST:event_brnBrisanjeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        txtRacunanje.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        if (txtRacunanje.getText().isEmpty() || txtRacunanje.getText() == null) {
            JOptionPane.showMessageDialog(null, "Prvo unesite broj");
            return;
        }
        if (txtRacunanje.getText().endsWith("+") || txtRacunanje.getText().endsWith("+") || txtRacunanje.getText().endsWith("-") || txtRacunanje.getText().endsWith("*") || txtRacunanje.getText().endsWith("/") || txtRacunanje.getText().endsWith(".") || txtRacunanje.getText().endsWith("%")) {
            txtRacunanje.setText(txtRacunanje.getText().substring(0, txtRacunanje.getText().length() - 1));
            txtRacunanje.setText(txtRacunanje.getText() + "%");
        } else {
            txtRacunanje.setText(txtRacunanje.getText() + "%");
        }
    }//GEN-LAST:event_btnModActionPerformed

    private void btnZagradaOtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZagradaOtvActionPerformed
        txtRacunanje.setText(txtRacunanje.getText() + "(");
    }//GEN-LAST:event_btnZagradaOtvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnBrisanje;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDjeljenje;
    private javax.swing.JButton btnMnozenje;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnOduzimanje;
    private javax.swing.JButton btnRezultat;
    private javax.swing.JButton btnTocka;
    private javax.swing.JButton btnZagradaOtv;
    private javax.swing.JButton btnZagradaZat;
    private javax.swing.JButton btnZbrajanje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtRacunanje;
    // End of variables declaration//GEN-END:variables

}
