/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kolokvij.zadatak4;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Bole
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGlavni = new javax.swing.JPanel();
        txtBroj1 = new javax.swing.JTextField();
        lblOperacija = new javax.swing.JLabel();
        txtBroj2 = new javax.swing.JTextField();
        btnZbrajanje = new javax.swing.JButton();
        btnOduzimanje = new javax.swing.JButton();
        btnDjeljenje = new javax.swing.JButton();
        btnMnozenje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        txtBroj1.setText("Unesite 1.broj.");

        lblOperacija.setText("Operacija");

        txtBroj2.setText("Unesite 2.broj.");

        btnZbrajanje.setText("+");
        btnZbrajanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZbrajanjeActionPerformed(evt);
            }
        });

        btnOduzimanje.setText("-");
        btnOduzimanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOduzimanjeActionPerformed(evt);
            }
        });

        btnDjeljenje.setText("/");
        btnDjeljenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDjeljenjeActionPerformed(evt);
            }
        });

        btnMnozenje.setText("*");
        btnMnozenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMnozenjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGlavniLayout = new javax.swing.GroupLayout(pnlGlavni);
        pnlGlavni.setLayout(pnlGlavniLayout);
        pnlGlavniLayout.setHorizontalGroup(
            pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGlavniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBroj2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBroj1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOperacija, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlGlavniLayout.createSequentialGroup()
                        .addComponent(btnZbrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOduzimanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlGlavniLayout.createSequentialGroup()
                        .addComponent(btnDjeljenje, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMnozenje, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlGlavniLayout.setVerticalGroup(
            pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGlavniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBroj1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblOperacija, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBroj2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZbrajanje)
                    .addComponent(btnOduzimanje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDjeljenje)
                    .addComponent(btnMnozenje))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(pnlGlavni);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZbrajanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZbrajanjeActionPerformed
        try {
            JOptionPane.showMessageDialog(null, Double.parseDouble(txtBroj1.getText()) + Integer.parseInt(txtBroj2.getText()));
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Unesite Broj!");
        }
        lblOperacija.setText("+");
    }//GEN-LAST:event_btnZbrajanjeActionPerformed

    private void btnOduzimanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOduzimanjeActionPerformed
        try {
            JOptionPane.showMessageDialog(null, Double.parseDouble(txtBroj1.getText()) - Integer.parseInt(txtBroj2.getText()));
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Unesite Broj!");
        }
        lblOperacija.setText("-");
    }//GEN-LAST:event_btnOduzimanjeActionPerformed

    private void btnDjeljenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDjeljenjeActionPerformed
        try {
            JOptionPane.showMessageDialog(null, Double.parseDouble(txtBroj1.getText()) / Integer.parseInt(txtBroj2.getText()));
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Unesite Broj!");
        }
        lblOperacija.setText("/");
    }//GEN-LAST:event_btnDjeljenjeActionPerformed

    private void btnMnozenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMnozenjeActionPerformed
        try {
            JOptionPane.showMessageDialog(null, Double.parseDouble(txtBroj1.getText()) * Integer.parseInt(txtBroj2.getText()));
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Unesite Broj!");
        }
        lblOperacija.setText("*");
    }//GEN-LAST:event_btnMnozenjeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDjeljenje;
    private javax.swing.JButton btnMnozenje;
    private javax.swing.JButton btnOduzimanje;
    private javax.swing.JButton btnZbrajanje;
    private javax.swing.JLabel lblOperacija;
    private javax.swing.JPanel pnlGlavni;
    private javax.swing.JTextField txtBroj1;
    private javax.swing.JTextField txtBroj2;
    // End of variables declaration//GEN-END:variables
}
